FROM python:3.12.2

RUN <<EOF
apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main/ nodejs && 
apk add --no-cache git zsh pipx shadow &&
pipx install poetry &&
chsh -s /bin/zsh
EOF

ENTRYPOINT [ "/bin/zsh", "-c" ]